export default {
  nb: {
    'menucard.page.title': 'Min side kvalifikasjoner',
    'menucard.icontile.course.title': 'Meld inn kurs eller utdanning',
    'menucard.icontile.seagoing.title': 'Meld inn fartstid',
    'menucard.icontile.competence.title': 'Meld inn tilleggskompetanse',
    'menucard.icontile.assessor.title': 'Meld inn assessorbedømmelse',
    'menucard.icontile.report.title': 'Rapporter',
    'reportseagoing.header.title': 'Meld inn fartstid',
    'reportseagoing.error.message': 'Ugyldig kombinasjon av personnummer, fornavn og etternavn.',
    'reportseagoing.input.personnumber': 'Lim inn D-/personnummer',
    'reportseagoing.input.firstname': 'Fornavn',
    'reportseagoing.input.lastname': 'Etternavn',
    'reportseagoing.button.addmore.title': 'Legg til mer fartstid',
    'reportseagoing.button.add.title': 'Legg til',
    'reportseagoing.input.enlistment.title': 'Påmønstringsdato',
    'reportseagoing.input.disembarkment.title': 'Avmønstringsdato',
    'reportseagoing.input.hours.title': 'Timer',
    'reportseagoing.addnew.button.title': 'Legg til ny fartstid ',
    'reportseagoing.cardheader.title': 'Bekreftelse',
    'reportseagoing.confirmation.text':
      'Takk, vi har mottatt din melding for fartstid knyttet til {name}, på fartøy {vessel}. Du finner oversikt over all innsendt fartstid under rapporter.',
    'reportCourse.page.title': 'Kurs og utdannelse',
    'reportcourceandeducation.header.title': 'Meld inn fullførte kurs',
    'reportcourceandeducation.summary.cardheader.title': 'Oppsummering',
    'reportcourceandeducation.input.course': 'Søk blant kurs',
    'reportcourceandeducation.input.datecomplete': 'Dato for fullført/bestått kurs',
    'reportcourceandeducation.card.course.title': 'Kurs',
    'reportcourceandeducation.card.date.title': 'Fullført/Bestått dato',
    'reportcourceandeducation.card.change': 'Endre',
    'reportcourceandeducation.card.save': 'Lagre',
    'reportcourceandeducation.button.addNew.title': 'Legg til nytt kurs',
    'reportcourceandeducation.button.addmore.title': 'Legg til flere deltagere',
    'registeradditionalcompetence.page.title': 'Tilleggskompetanse',
    'registeradditionalcompetence.header.title': 'Meld inn tilleggskompetanse',
    'registeradditionalcompetence.card.person.name': 'Navn',
    'registeradditionalcompetence.card.person.personnumber': 'Personnummer',
    'registeradditionalcompetence.input.personnumber': 'D-/Personnummer',
    'registeradditionalcompetence.input.firstname': 'Fornavn',
    'registeradditionalcompetence.input.lastname': 'Etternavn',
    'registeradditionalcompetence.input.vesselsearch': 'Fartøysøk',
    'registeradditionalcompetence.input.competence': 'Kompetanse',
    'registeradditionalcompetence.input.fromdate': 'Fra dato',
    'registeradditionalcompetence.input.todate': 'Til dato',
    'registeradditionalcompetence.card.competence.title': 'Tilleggskompetanse',
    'registeradditionalcompetence.card.vessel.title': 'Fartøy',
    'registeradditionalcompetence.card.fromdate.title': 'Fra dato',
    'registeradditionalcompetence.card.todate.title': 'Til dato',
    'registeradditionalcompetence.card.save': 'Lagre',
    'registeradditionalcompetence.card.change': 'Endre',
    'registeradditionalcompetence.confirmation.header.title': 'Bekreftelse',
    'registeradditionalcompetence.addnew.button.title': 'Legg til ny tilleggskompetanse',
    'registeradditionalcompetence.confirmation.text':
      'Takk, vi har mottatt din melding for {person} om tilleggskompetanse {competence}. Du finner oversikt over alle innmeldinger under rapporter.',
    'reportcourceandeducation.confirmation.text':
      'Takk, vi har mottatt din melding for {participants} deltakere som har bestått kurset {course}. Du finner oversikt over all innmeldinger under rapporter.',
    'datacard.certificates.title': 'Sertifikater',
    'datacard.courseandeducation.title': 'Kurs & Utdanning',
    'datacard.profilevisits.title': 'Profilbesøk',
    'datacard.charges.title': 'Gebyrer',
    'datacard.searches.title': 'Søknader',
    'datacard.seafarer.title': 'Sjømann',
    'datacard.seagoing.title': 'Fartstid',
    'datacard.competence.title': 'Annen kompetanse',
    'link.back.title': 'Tilbake',
    'button.next.title': 'Neste',
    'button.send.title': 'Send inn',
    'error.general': 'Noe gikk galt, prøv igjen senere.',
    'error.noResult': 'Ingen resultater funnet.',
    'assessment.heading': 'Meld inn assessorbedømmelse',
    'assessment.page.title': 'Assessorbedømmelse',
    'general.delete': 'slett'
  },
  en: {
    'menucard.page.title': 'My qualifications',
    'menucard.icontile.course.title': 'Register course or education',
    'menucard.icontile.seagoing.title': 'Register sea going time',
    'menucard.icontile.competence.title': 'Register additional competence',
    'menucard.icontile.assessor.title': 'Submit assessor assessment',
    'menucard.icontile.report.title': 'Reports',
    'reportseagoing.header.title': 'Send in sea going time',
    'reportseagoing.error.message':
      'Invalid combination of personal number, first name and last name.',
    'reportseagoing.input.personnumber': 'Paste D-Number/Personal number',
    'reportseagoing.input.firstname': 'First name',
    'reportseagoing.input.lastname': 'Last name',
    'reportseagoing.button.addmore.title': 'Add more seagoing time',
    'reportseagoing.button.add.title': 'Add seagoing time',
    'reportseagoing.input.enlistment.title': 'Enlistment date',
    'reportseagoing.input.disembarkment.title': 'Disembarkment date',
    'reportseagoing.input.hours.title': 'Hours',
    'reportseagoing.cardheader.title': 'Confirmation',
    'reportseagoing.addnew.button.title': 'Add more seagoing time ',
    'reportseagoing.confirmation.text':
      'Thank you, we have recieved your report for seagoing time for {name}, on vessel {vessel}. You will find an overview of all registrations under reports.',
    'reportCourse.page.title': 'Courses and education',
    'reportcourceandeducation.header.title': 'Enroll completed courses',
    'reportcourceandeducation.summary.cardheader.title': 'Summary',
    'reportcourceandeducation.input.course': 'Search courses',
    'reportcourceandeducation.input.datecomplete': 'Date of completed/passed course',
    'reportcourceandeducation.card.course.title': 'Course',
    'reportcourceandeducation.card.date.title': 'Completed/Passed date',
    'reportcourceandeducation.card.change': 'Change',
    'reportcourceandeducation.card.save': 'Save',
    'reportcourceandeducation.button.addNew.title': 'Add new course',
    'reportcourceandeducation.button.addmore.title': 'Add more participants',
    'registeradditionalcompetence.page.title': 'Additional competence',
    'registeradditionalcompetence.input.personnumber': 'D-/Personnumber',
    'registeradditionalcompetence.input.firstname': 'Firstname',
    'registeradditionalcompetence.input.lastname': 'Lastname',
    'registeradditionalcompetence.input.vesselsearch': 'Vessel search',
    'registeradditionalcompetence.input.competence': 'Competence',
    'registeradditionalcompetence.input.fromdate': 'From date',
    'registeradditionalcompetence.input.todate': 'To date',
    'registeradditionalcompetence.card.competence.title': 'Additional competence',
    'registeradditionalcompetence.card.vessel.title': 'Vessel',
    'registeradditionalcompetence.card.fromdate.title': 'From date',
    'registeradditionalcompetence.card.todate.title': 'To date',
    'registeradditionalcompetence.header.title': 'Register additional competence',
    'registeradditionalcompetence.card.person.name': 'Name',
    'registeradditionalcompetence.card.person.personnumber': 'D-Number',
    'registeradditionalcompetence.card.save': 'Save',
    'registeradditionalcompetence.card.change': 'Edit',
    'registeradditionalcompetence.confirmation.header.title': 'Confirmation',
    'registeradditionalcompetence.addnew.button.title': 'Add new additional competence',
    'registeradditionalcompetence.confirmation.text':
      'Thank you, we have recieved your report for {name} of additional competence {competence}. You will find an overview of all registrations under reports.',
    'reportcourceandeducation.confirmation.text':
      'Thank you, we have recieved your report for {participants} participants who has completed the course {course}. You will find an overview of all registrations under reports.',
    'datacard.certificates.title': 'Certificates',
    'datacard.courseandeducation.title': 'Courses & Education',
    'datacard.profilevisits.title': 'Profile visits',
    'datacard.charges.title': 'Charges',
    'datacard.searches.title': 'Applications',
    'datacard.seafarer.title': 'Seafarer',
    'datacard.seagoing.title': 'Seagoing',
    'datacard.competence.title': 'Other competencies',
    'link.back.title': 'Back',
    'button.next.title': 'Next',
    'button.send.title': 'Send',
    'error.general': 'Something went wrong, please try again later.',
    'error.noResult': 'No result found.',
    'assessment.heading': 'Submit assessment',
    'assessment.page.title': 'Assessor rating',
    'general.delete': 'delete'
  }
};
