export const SET_USER = 'SET_USER';
export const SET_VESSEL = 'SET_VESSEL';
export const SET_SEAGOING_PERSON = 'SET_SEAGOING_PERSON';
export const SET_COURSE_AND_EDUCATION = 'SET_COURSE_AND_EDUCATION';
export const SET_SEAGOING_DETAILS = 'SET_SEAGOING_DETAILS';
export const SET_ADDITIONAL_COMPETENCE_PERSON = 'SET_ADDITIONAL_COMPETENCE_PERSON';
export const SET_ADDITIONAL_COMPETENCE = 'SET_ADDITIONAL_COMPETENCE';
export const SET_ASSESSMENT_DETAILS = 'SET_ASSESSMENT_DETAILS';
